# @package _global_
defaults:
  - hydra/job_logging: custom
  - hydra/hydra_logging: colorlog
#  - job: train/deblurmasked
  - job: train/deblurframe2
#  - job: train/unet
#  - job: train/deblurmaskdistill
#  - job: train/blured-gray.yaml
#  - job: train/uformer-gray
hydra:
  run:
    dir: ${working_dir}/outputs/${name}-${now:%Y-%m-%d_%H-%M-%S}